[build]
  command = "npm run build"
  publish = ".next"

[context.production.environment]
  NEXT_PUBLIC_API_BASE = "https://api.example.com"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
